/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = ('processing' | 'completed' | 'cancelled' | 'refunded') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'checkout-sessions': CheckoutSession;
    pages: Page;
    categories: Category;
    media: Media;
    'digital-assets': DigitalAsset;
    'digital-stock-units': DigitalStockUnit;
    'download-access': DownloadAccess;
    'download-logs': DownloadLog;
    licenses: License;
    'payment-transactions': PaymentTransaction;
    coupons: Coupon;
    'promo-banners': PromoBanner;
    testimonials: Testimonial;
    'support-tickets': SupportTicket;
    'support-messages': SupportMessage;
    'email-templates': EmailTemplate;
    'stock-reservations': StockReservation;
    'stock-ledger': StockLedger;
    waitlists: Waitlist;
    'waitlist-entries': WaitlistEntry;
    forms: Form;
    'form-submissions': FormSubmission;
    addresses: Address;
    variants: Variant;
    variantTypes: VariantType;
    variantOptions: VariantOption;
    products: Product;
    carts: Cart;
    orders: Order;
    transactions: Transaction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      orders: 'orders';
      cart: 'carts';
      addresses: 'addresses';
    };
    waitlists: {
      entries: 'waitlist-entries';
    };
    variantTypes: {
      options: 'variantOptions';
    };
    products: {
      variants: 'variants';
      digitalAssets: 'digital-assets';
      digitalStockUnits: 'digital-stock-units';
      stockReservations: 'stock-reservations';
      stockHistory: 'stock-ledger';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'checkout-sessions': CheckoutSessionsSelect<false> | CheckoutSessionsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'digital-assets': DigitalAssetsSelect<false> | DigitalAssetsSelect<true>;
    'digital-stock-units': DigitalStockUnitsSelect<false> | DigitalStockUnitsSelect<true>;
    'download-access': DownloadAccessSelect<false> | DownloadAccessSelect<true>;
    'download-logs': DownloadLogsSelect<false> | DownloadLogsSelect<true>;
    licenses: LicensesSelect<false> | LicensesSelect<true>;
    'payment-transactions': PaymentTransactionsSelect<false> | PaymentTransactionsSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    'promo-banners': PromoBannersSelect<false> | PromoBannersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'support-tickets': SupportTicketsSelect<false> | SupportTicketsSelect<true>;
    'support-messages': SupportMessagesSelect<false> | SupportMessagesSelect<true>;
    'email-templates': EmailTemplatesSelect<false> | EmailTemplatesSelect<true>;
    'stock-reservations': StockReservationsSelect<false> | StockReservationsSelect<true>;
    'stock-ledger': StockLedgerSelect<false> | StockLedgerSelect<true>;
    waitlists: WaitlistsSelect<false> | WaitlistsSelect<true>;
    'waitlist-entries': WaitlistEntriesSelect<false> | WaitlistEntriesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    variantTypes: VariantTypesSelect<false> | VariantTypesSelect<true>;
    variantOptions: VariantOptionsSelect<false> | VariantOptionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    settings: Setting;
    'stock-adjustment': StockAdjustment;
    'whatsapp-blast-test': WhatsappBlastTest;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'stock-adjustment': StockAdjustmentSelect<false> | StockAdjustmentSelect<true>;
    'whatsapp-blast-test': WhatsappBlastTestSelect<false> | WhatsappBlastTestSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      addresses: Address;
      carts: Cart;
      customers?: User;
      orders: Order;
      products: Product;
      transactions: Transaction;
      variantOptions: VariantOption;
      variants: Variant;
      variantTypes: VariantType;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles?: ('admin' | 'manager' | 'finance' | 'support' | 'customer')[] | null;
  googleId?: string | null;
  googleAvatarURL?: string | null;
  avatar?: (number | null) | Media;
  phone?: string | null;
  status?: ('active' | 'inactive' | 'blocked') | null;
  memberTier?: ('bronze' | 'silver' | 'gold' | 'diamond') | null;
  totalSpentIDR?: number | null;
  membershipPoints?: number | null;
  memberSince?: string | null;
  deleteAccountRequestedAt?: string | null;
  deleteAccountReason?: string | null;
  orders?: {
    docs?: (number | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  cart?: {
    docs?: (number | Cart)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  addresses?: {
    docs?: (number | Address)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  uploadedBy?: (number | null) | User;
  isSupportAttachment?: boolean | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  customer?: (number | null) | User;
  customerEmail?: string | null;
  transactions?: (number | Transaction)[] | null;
  status?: OrderStatus;
  amount?: number | null;
  currency?: ('IDR' | 'USD') | null;
  pointsEarned?: number | null;
  paymentReference?: string | null;
  accessToken?: string | null;
  voucher?: (number | null) | Coupon;
  voucherCode?: string | null;
  subtotalBeforeDiscount?: number | null;
  discountAmount?: number | null;
  memberTierSnapshot?: ('bronze' | 'silver' | 'gold' | 'diamond') | null;
  /**
   * Snapshot hasil assignment stok digital per unit. Customer hanya melihat data miliknya dari order ini.
   */
  digitalDeliveries?:
    | {
        product: number | Product;
        productTitle?: string | null;
        variant?: string | null;
        variantTitle?: string | null;
        quantity: number;
        units?:
          | {
              unitCode?: string | null;
              deliveryType?: ('credentials' | 'file' | 'text') | null;
              label?: string | null;
              accountEmail?: string | null;
              accountUsername?: string | null;
              accountPassword?: string | null;
              loginUrl?: string | null;
              referenceCode?: string | null;
              content?: string | null;
              file?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Short storefront summary for product cards and hero sections.
   */
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        image: number | Media;
        variantOption?: (number | null) | VariantOption;
        id?: string | null;
      }[]
    | null;
  layout?: (CallToActionBlock | ContentBlock | MediaBlock)[] | null;
  includedFiles?:
    | {
        label: string;
        format?: string | null;
        size?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Panduan cara penggunaan produk ini. Akan ditampilkan di halaman order setelah pembayaran berhasil.
   */
  caraPenggunaan?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Informasi garansi produk. Akan ditampilkan di halaman order setelah pembayaran berhasil.
   */
  garansi?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  productFAQ?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  inventory?: number | null;
  enableVariants?: boolean | null;
  variantTypes?: (number | VariantType)[] | null;
  variants?: {
    docs?: (number | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  priceInIDREnabled?: boolean | null;
  priceInIDR?: number | null;
  priceInUSDEnabled?: boolean | null;
  priceInUSD?: number | null;
  relatedProducts?: (number | Product)[] | null;
  productType?: ('digital' | 'license_key' | 'ebook' | 'template' | 'source_code' | 'ui_kit' | 'prompt_pack') | null;
  /**
   * Gunakan per-unit digital stock jika setiap stok harus punya akun/file/catatan unik sendiri.
   */
  digitalFulfillmentMode?: ('standard' | 'per_unit_stock') | null;
  licenseType?: ('standard' | 'extended' | 'personal' | 'commercial' | 'unlimited') | null;
  version?: string | null;
  updatePolicy?: string | null;
  refundPolicy?: string | null;
  isFeatured?: boolean | null;
  badge?: ('new' | 'best_seller' | 'discount') | null;
  digitalAssets?: {
    docs?: (number | DigitalAsset)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Unit stok digital per akun/file. Untuk produk mode ini, stok sebaiknya ditambah lewat Stock Adjustment agar jumlah stok dan data unit tetap sinkron.
   */
  digitalStockUnits?: {
    docs?: (number | DigitalStockUnit)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  promo?: {
    isFlashSale?: boolean | null;
    /**
     * Enter discount percentage (1-99)
     */
    discountPercent?: number | null;
    flashSaleEndDate?: string | null;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  categories?: (number | Category)[] | null;
  /**
   * Reservasi stok aktif untuk produk ini.
   */
  stockReservations?: {
    docs?: (number | StockReservation)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Riwayat semua perubahan stok produk ini.
   */
  stockHistory?: {
    docs?: (number | StockLedger)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions".
 */
export interface VariantOption {
  id: number;
  _variantOptions_options_order?: string | null;
  variantType: number | VariantType;
  label: string;
  /**
   * should be defaulted or dynamic based on label
   */
  value: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes".
 */
export interface VariantType {
  id: number;
  label: string;
  name: string;
  options?: {
    docs?: (number | VariantOption)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  publishedOn?: string | null;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact' | 'flashSale';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | CarouselBlock
    | ThreeItemGridBlock
    | BannerBlock
    | FormBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocsTotal?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock".
 */
export interface ThreeItemGridBlock {
  products?: (number | Product)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'threeItemGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  /**
   * Used for administrative purposes, not shown to customers. This is populated by default.
   */
  title?: string | null;
  product: number | Product;
  options: (number | VariantOption)[];
  inventory?: number | null;
  priceInIDREnabled?: boolean | null;
  priceInIDR?: number | null;
  priceInUSDEnabled?: boolean | null;
  priceInUSD?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "digital-assets".
 */
export interface DigitalAsset {
  id: number;
  product: number | Product;
  file: number | Media;
  fileName: string;
  /**
   * File size in bytes
   */
  fileSize?: number | null;
  version?: string | null;
  changelog?: string | null;
  protected?: boolean | null;
  status: 'active' | 'draft' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * Stok digital per unit, misalnya akun email/password, catatan akses, atau file per stok.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "digital-stock-units".
 */
export interface DigitalStockUnit {
  id: number;
  unitCode: string;
  product: number | Product;
  /**
   * Variant ID jika stok unit ini khusus untuk variant tertentu.
   */
  variant?: string | null;
  status: 'available' | 'reserved' | 'assigned' | 'archived';
  deliveryType: 'credentials' | 'file' | 'text';
  /**
   * Label internal, misalnya Slot 1, Akun batch Juli, atau PDF pack.
   */
  label?: string | null;
  accountEmail?: string | null;
  accountUsername?: string | null;
  accountPassword?: string | null;
  loginUrl?: string | null;
  /**
   * Kode internal atau catatan singkat lain yang mau ikut dikirim.
   */
  referenceCode?: string | null;
  /**
   * Catatan bebas: OTP backup, instruksi aktivasi, teks lisensi, dll.
   */
  content?: string | null;
  file?: (number | null) | Media;
  reservationId?: string | null;
  customer?: (number | null) | User;
  order?: (number | null) | Order;
  assignedAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kartu stok sementara — reservasi stok selama proses pembayaran.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-reservations".
 */
export interface StockReservation {
  id: number;
  /**
   * ID unik reservasi (biasanya = paymentIntentID / cartID + timestamp)
   */
  reservationId: string;
  product: number | Product;
  /**
   * Variant ID jika produk menggunakan variant. Kosong jika tidak.
   */
  variant?: string | null;
  quantity: number;
  status: 'pending' | 'confirmed' | 'released';
  /**
   * Waktu reservasi expired. Default: 10 menit dari waktu dibuat.
   */
  expiresAt: string;
  /**
   * Diisi setelah pembayaran berhasil.
   */
  order?: (number | null) | Order;
  customer?: (number | null) | User;
  /**
   * Cart ID yang memicu reservasi ini.
   */
  cartId?: string | null;
  /**
   * Catatan tambahan (misal: alasan release).
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kartu stok permanen — riwayat semua perubahan inventory produk.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-ledger".
 */
export interface StockLedger {
  id: number;
  /**
   * Produk yang stoknya berubah.
   */
  product: number | Product;
  /**
   * Variant ID jika produk menggunakan variant. Kosong jika tidak.
   */
  variant?: string | null;
  /**
   * Jenis perubahan stok.
   */
  type: 'in' | 'out' | 'reserved' | 'released' | 'adjust';
  /**
   * Jumlah perubahan. Positif = stok bertambah, negatif = stok berkurang.
   */
  qty: number;
  /**
   * Saldo stok SEBELUM transaksi ini.
   */
  stockBefore: number;
  /**
   * Saldo stok SETELAH transaksi ini.
   */
  stockAfter: number;
  /**
   * ID referensi (reservationId, orderId, atau keterangan manual).
   */
  referenceId?: string | null;
  /**
   * Order terkait (jika ada).
   */
  order?: (number | null) | Order;
  /**
   * Customer terkait (jika ada).
   */
  customer?: (number | null) | User;
  /**
   * Admin/staff yang melakukan perubahan (untuk penyesuaian manual).
   */
  performedBy?: (number | null) | User;
  /**
   * Catatan tambahan.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  paymentMethod?: ('pakasir' | 'nowpayments') | null;
  pakasir?: {
    pakasirOrderID?: string | null;
  };
  nowpayments?: {
    nowpaymentsPaymentID?: string | null;
    payCurrency?: string | null;
  };
  billingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  status: 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (number | null) | User;
  customerEmail?: string | null;
  order?: (number | null) | Order;
  cart?: (number | null) | Cart;
  amount?: number | null;
  currency?: ('IDR' | 'USD') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  secret?: string | null;
  customer?: (number | null) | User;
  purchasedAt?: string | null;
  status?: ('active' | 'purchased' | 'abandoned') | null;
  subtotal?: number | null;
  currency?: ('IDR' | 'USD') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  title: string;
  description?: string | null;
  benefitSummary?: string | null;
  codeMode: 'manual' | 'auto';
  /**
   * Prefix untuk kode otomatis, mis. MEMBER atau GOLD.
   */
  codePrefix?: string | null;
  code: string;
  discountType: 'percentage' | 'fixed';
  amount: number;
  allowedTiers?: ('bronze' | 'silver' | 'gold' | 'diamond')[] | null;
  minimumSpend?: number | null;
  usageLimit?: number | null;
  perUserLimit?: number | null;
  usedCount?: number | null;
  startsAt?: string | null;
  ttlHours?: number | null;
  expiresAt?: string | null;
  status: 'active' | 'inactive' | 'expired';
  /**
   * Centang lalu simpan untuk kirim voucher ini ke semua customer/member yang punya nomor WhatsApp.
   */
  sendWhatsAppBlast?: boolean | null;
  whatsAppBlastSentAt?: string | null;
  whatsAppBlastRecipientCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number;
  customer?: (number | null) | User;
  title?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country:
    | 'US'
    | 'GB'
    | 'CA'
    | 'AU'
    | 'AT'
    | 'BE'
    | 'BR'
    | 'BG'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'EE'
    | 'FI'
    | 'FR'
    | 'DE'
    | 'GR'
    | 'HK'
    | 'HU'
    | 'IN'
    | 'IE'
    | 'IT'
    | 'JP'
    | 'LV'
    | 'LT'
    | 'LU'
    | 'MY'
    | 'MT'
    | 'MX'
    | 'NL'
    | 'NZ'
    | 'NO'
    | 'PL'
    | 'PT'
    | 'RO'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'ES'
    | 'SE'
    | 'CH';
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checkout-sessions".
 */
export interface CheckoutSession {
  id: number;
  sessionId: string;
  activeKey?: string | null;
  customer: number | User;
  status: 'creating' | 'pending' | 'completed' | 'cancelled' | 'expired';
  expiresAt: string;
  reservationId?: string | null;
  cartId?: string | null;
  currency: 'IDR' | 'USD';
  paymentMethod: 'pakasir' | 'nowpayments';
  paymentData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  order?: (number | null) | Order;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "download-access".
 */
export interface DownloadAccess {
  id: number;
  customer: number | User;
  product: number | Product;
  order: number | Order;
  asset: number | DigitalAsset;
  status: 'active' | 'expired' | 'revoked';
  maxDownloads?: number | null;
  downloadCount?: number | null;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "download-logs".
 */
export interface DownloadLog {
  id: number;
  customer: number | User;
  product: number | Product;
  asset: number | DigitalAsset;
  order: number | Order;
  ip?: string | null;
  userAgent?: string | null;
  downloadedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "licenses".
 */
export interface License {
  id: number;
  customer: number | User;
  product: number | Product;
  order: number | Order;
  licenseKey: string;
  status: 'active' | 'inactive' | 'expired' | 'revoked';
  maxActivations?: number | null;
  activationCount?: number | null;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-transactions".
 */
export interface PaymentTransaction {
  id: number;
  order: number | Order;
  customer: number | User;
  provider: 'stripe' | 'midtrans' | 'xendit' | 'manual' | 'dummy';
  providerTransactionId: string;
  amount: number;
  currency: string;
  status: 'created' | 'waiting_payment' | 'settlement' | 'capture' | 'deny' | 'cancel' | 'expire' | 'refund';
  rawPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-banners".
 */
export interface PromoBanner {
  id: number;
  /**
   * Internal title for admin reference
   */
  title: string;
  /**
   * Recommended size: 1920x400px (wide banner)
   */
  image: number | Media;
  /**
   * Optional link when banner is clicked
   */
  link?: string | null;
  status: 'draft' | 'published';
  /**
   * Higher number = shown first (0 = lowest priority)
   */
  priority?: number | null;
  /**
   * When should this banner start showing?
   */
  startDate?: string | null;
  /**
   * When should this banner stop showing?
   */
  endDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  /**
   * e.g., "Marketing Manager", "Freelance Designer"
   */
  role: string;
  /**
   * Customer photo (optional)
   */
  avatar?: (number | null) | Media;
  /**
   * Testimonial text in Indonesian
   */
  commentId: string;
  /**
   * Testimonial text in English
   */
  commentEn: string;
  rating: number;
  status: 'draft' | 'published';
  /**
   * Higher number = shown first
   */
  priority?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-tickets".
 */
export interface SupportTicket {
  id: number;
  ticketNumber?: string | null;
  customer: number | User;
  relatedOrder?: (number | null) | Order;
  relatedProduct?: (number | null) | Product;
  subject: string;
  category:
    | 'payment_issue'
    | 'download_problem'
    | 'license_key_problem'
    | 'product_access_problem'
    | 'refund_request'
    | 'technical_support'
    | 'general_question';
  priority: 'low' | 'medium' | 'high' | 'urgent';
  status: 'open' | 'waiting_customer' | 'in_progress' | 'resolved' | 'closed';
  assignedTo?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-messages".
 */
export interface SupportMessage {
  id: number;
  ticket: number | SupportTicket;
  sender: number | User;
  senderRole: 'customer' | 'admin' | 'support';
  message: string;
  attachments?:
    | {
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  isInternalNote?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates".
 */
export interface EmailTemplate {
  id: number;
  name: string;
  subject: string;
  body: string;
  type:
    | 'welcome'
    | 'order_paid'
    | 'payment_pending'
    | 'download_ready'
    | 'license_created'
    | 'support_reply'
    | 'password_reset';
  status: 'active' | 'inactive';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlists".
 */
export interface Waitlist {
  id: number;
  /**
   * Produk yang sedang habis stok dan dibuka waiting list.
   */
  product: number | Product;
  status: 'active' | 'closed';
  /**
   * Opsional: Voucher diskon yang akan diberikan ke member waiting list saat stok tersedia kembali.
   */
  voucher?: (number | null) | Coupon;
  /**
   * Pesan custom yang dikirim saat stok tersedia. Gunakan {{name}}, {{product}}, {{voucher}} sebagai placeholder.
   */
  notifyMessage?: string | null;
  entries?: {
    docs?: (number | WaitlistEntry)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  totalEntries?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist-entries".
 */
export interface WaitlistEntry {
  id: number;
  waitlist: number | Waitlist;
  /**
   * User yang terdaftar (jika login).
   */
  customer?: (number | null) | User;
  /**
   * Nama customer (untuk guest atau display).
   */
  name?: string | null;
  /**
   * Nomor WhatsApp untuk notifikasi saat stok tersedia.
   */
  phone: string;
  /**
   * Jumlah unit yang diinginkan.
   */
  quantity: number;
  status: 'waiting' | 'notified' | 'purchased' | 'cancelled';
  notifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'checkout-sessions';
        value: number | CheckoutSession;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'digital-assets';
        value: number | DigitalAsset;
      } | null)
    | ({
        relationTo: 'digital-stock-units';
        value: number | DigitalStockUnit;
      } | null)
    | ({
        relationTo: 'download-access';
        value: number | DownloadAccess;
      } | null)
    | ({
        relationTo: 'download-logs';
        value: number | DownloadLog;
      } | null)
    | ({
        relationTo: 'licenses';
        value: number | License;
      } | null)
    | ({
        relationTo: 'payment-transactions';
        value: number | PaymentTransaction;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null)
    | ({
        relationTo: 'promo-banners';
        value: number | PromoBanner;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'support-tickets';
        value: number | SupportTicket;
      } | null)
    | ({
        relationTo: 'support-messages';
        value: number | SupportMessage;
      } | null)
    | ({
        relationTo: 'email-templates';
        value: number | EmailTemplate;
      } | null)
    | ({
        relationTo: 'stock-reservations';
        value: number | StockReservation;
      } | null)
    | ({
        relationTo: 'stock-ledger';
        value: number | StockLedger;
      } | null)
    | ({
        relationTo: 'waitlists';
        value: number | Waitlist;
      } | null)
    | ({
        relationTo: 'waitlist-entries';
        value: number | WaitlistEntry;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'addresses';
        value: number | Address;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'variantTypes';
        value: number | VariantType;
      } | null)
    | ({
        relationTo: 'variantOptions';
        value: number | VariantOption;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  googleId?: T;
  googleAvatarURL?: T;
  avatar?: T;
  phone?: T;
  status?: T;
  memberTier?: T;
  totalSpentIDR?: T;
  membershipPoints?: T;
  memberSince?: T;
  deleteAccountRequestedAt?: T;
  deleteAccountReason?: T;
  orders?: T;
  cart?: T;
  addresses?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checkout-sessions_select".
 */
export interface CheckoutSessionsSelect<T extends boolean = true> {
  sessionId?: T;
  activeKey?: T;
  customer?: T;
  status?: T;
  expiresAt?: T;
  reservationId?: T;
  cartId?: T;
  currency?: T;
  paymentMethod?: T;
  paymentData?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  publishedOn?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        threeItemGrid?: T | ThreeItemGridBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock_select".
 */
export interface CarouselBlockSelect<T extends boolean = true> {
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  populatedDocs?: T;
  populatedDocsTotal?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock_select".
 */
export interface ThreeItemGridBlockSelect<T extends boolean = true> {
  products?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  style?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  uploadedBy?: T;
  isSupportAttachment?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "digital-assets_select".
 */
export interface DigitalAssetsSelect<T extends boolean = true> {
  product?: T;
  file?: T;
  fileName?: T;
  fileSize?: T;
  version?: T;
  changelog?: T;
  protected?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "digital-stock-units_select".
 */
export interface DigitalStockUnitsSelect<T extends boolean = true> {
  unitCode?: T;
  product?: T;
  variant?: T;
  status?: T;
  deliveryType?: T;
  label?: T;
  accountEmail?: T;
  accountUsername?: T;
  accountPassword?: T;
  loginUrl?: T;
  referenceCode?: T;
  content?: T;
  file?: T;
  reservationId?: T;
  customer?: T;
  order?: T;
  assignedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "download-access_select".
 */
export interface DownloadAccessSelect<T extends boolean = true> {
  customer?: T;
  product?: T;
  order?: T;
  asset?: T;
  status?: T;
  maxDownloads?: T;
  downloadCount?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "download-logs_select".
 */
export interface DownloadLogsSelect<T extends boolean = true> {
  customer?: T;
  product?: T;
  asset?: T;
  order?: T;
  ip?: T;
  userAgent?: T;
  downloadedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "licenses_select".
 */
export interface LicensesSelect<T extends boolean = true> {
  customer?: T;
  product?: T;
  order?: T;
  licenseKey?: T;
  status?: T;
  maxActivations?: T;
  activationCount?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-transactions_select".
 */
export interface PaymentTransactionsSelect<T extends boolean = true> {
  order?: T;
  customer?: T;
  provider?: T;
  providerTransactionId?: T;
  amount?: T;
  currency?: T;
  status?: T;
  rawPayload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  benefitSummary?: T;
  codeMode?: T;
  codePrefix?: T;
  code?: T;
  discountType?: T;
  amount?: T;
  allowedTiers?: T;
  minimumSpend?: T;
  usageLimit?: T;
  perUserLimit?: T;
  usedCount?: T;
  startsAt?: T;
  ttlHours?: T;
  expiresAt?: T;
  status?: T;
  sendWhatsAppBlast?: T;
  whatsAppBlastSentAt?: T;
  whatsAppBlastRecipientCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-banners_select".
 */
export interface PromoBannersSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  link?: T;
  status?: T;
  priority?: T;
  startDate?: T;
  endDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  avatar?: T;
  commentId?: T;
  commentEn?: T;
  rating?: T;
  status?: T;
  priority?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-tickets_select".
 */
export interface SupportTicketsSelect<T extends boolean = true> {
  ticketNumber?: T;
  customer?: T;
  relatedOrder?: T;
  relatedProduct?: T;
  subject?: T;
  category?: T;
  priority?: T;
  status?: T;
  assignedTo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-messages_select".
 */
export interface SupportMessagesSelect<T extends boolean = true> {
  ticket?: T;
  sender?: T;
  senderRole?: T;
  message?: T;
  attachments?:
    | T
    | {
        file?: T;
        id?: T;
      };
  isInternalNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates_select".
 */
export interface EmailTemplatesSelect<T extends boolean = true> {
  name?: T;
  subject?: T;
  body?: T;
  type?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-reservations_select".
 */
export interface StockReservationsSelect<T extends boolean = true> {
  reservationId?: T;
  product?: T;
  variant?: T;
  quantity?: T;
  status?: T;
  expiresAt?: T;
  order?: T;
  customer?: T;
  cartId?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-ledger_select".
 */
export interface StockLedgerSelect<T extends boolean = true> {
  product?: T;
  variant?: T;
  type?: T;
  qty?: T;
  stockBefore?: T;
  stockAfter?: T;
  referenceId?: T;
  order?: T;
  customer?: T;
  performedBy?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlists_select".
 */
export interface WaitlistsSelect<T extends boolean = true> {
  product?: T;
  status?: T;
  voucher?: T;
  notifyMessage?: T;
  entries?: T;
  totalEntries?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist-entries_select".
 */
export interface WaitlistEntriesSelect<T extends boolean = true> {
  waitlist?: T;
  customer?: T;
  name?: T;
  phone?: T;
  quantity?: T;
  status?: T;
  notifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  title?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  options?: T;
  inventory?: T;
  priceInIDREnabled?: T;
  priceInIDR?: T;
  priceInUSDEnabled?: T;
  priceInUSD?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes_select".
 */
export interface VariantTypesSelect<T extends boolean = true> {
  label?: T;
  name?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions_select".
 */
export interface VariantOptionsSelect<T extends boolean = true> {
  _variantOptions_options_order?: T;
  variantType?: T;
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  shortDescription?: T;
  description?: T;
  gallery?:
    | T
    | {
        image?: T;
        variantOption?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
      };
  includedFiles?:
    | T
    | {
        label?: T;
        format?: T;
        size?: T;
        id?: T;
      };
  caraPenggunaan?: T;
  garansi?: T;
  productFAQ?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  inventory?: T;
  enableVariants?: T;
  variantTypes?: T;
  variants?: T;
  priceInIDREnabled?: T;
  priceInIDR?: T;
  priceInUSDEnabled?: T;
  priceInUSD?: T;
  relatedProducts?: T;
  productType?: T;
  digitalFulfillmentMode?: T;
  licenseType?: T;
  version?: T;
  updatePolicy?: T;
  refundPolicy?: T;
  isFeatured?: T;
  badge?: T;
  digitalAssets?: T;
  digitalStockUnits?: T;
  promo?:
    | T
    | {
        isFlashSale?: T;
        discountPercent?: T;
        flashSaleEndDate?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  categories?: T;
  stockReservations?: T;
  stockHistory?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  secret?: T;
  customer?: T;
  purchasedAt?: T;
  status?: T;
  subtotal?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  customer?: T;
  customerEmail?: T;
  transactions?: T;
  status?: T;
  amount?: T;
  currency?: T;
  pointsEarned?: T;
  paymentReference?: T;
  accessToken?: T;
  voucher?: T;
  voucherCode?: T;
  subtotalBeforeDiscount?: T;
  discountAmount?: T;
  memberTierSnapshot?: T;
  digitalDeliveries?:
    | T
    | {
        product?: T;
        productTitle?: T;
        variant?: T;
        variantTitle?: T;
        quantity?: T;
        units?:
          | T
          | {
              unitCode?: T;
              deliveryType?: T;
              label?: T;
              accountEmail?: T;
              accountUsername?: T;
              accountPassword?: T;
              loginUrl?: T;
              referenceCode?: T;
              content?: T;
              file?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  paymentMethod?: T;
  pakasir?:
    | T
    | {
        pakasirOrderID?: T;
      };
  nowpayments?:
    | T
    | {
        nowpaymentsPaymentID?: T;
        payCurrency?: T;
      };
  billingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  cart?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  storeName: string;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  primaryColor?: string | null;
  supportEmail?: string | null;
  paymentConfig?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  emailConfig?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  storageConfig?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  commerce?: {
    /**
     * Saat nonaktif, switch USD disembunyikan di frontend dan checkout USD ditolak backend.
     */
    enableUSD?: boolean | null;
  };
  trustBadges?: {
    /**
     * Display value for total users (e.g., "10,000+")
     */
    totalUsers?: string | null;
    /**
     * Customer satisfaction percentage
     */
    satisfactionRate?: string | null;
    /**
     * Support hours (e.g., "24/7")
     */
    supportAvailability?: string | null;
    partnerLogos?:
      | {
          logo: number | Media;
          name: string;
          id?: string | null;
        }[]
      | null;
  };
  legalPages?: {
    termsPage?: (number | null) | Page;
    privacyPage?: (number | null) | Page;
    refundPage?: (number | null) | Page;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Tool untuk adjust stok produk (restock, koreksi, dll)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-adjustment".
 */
export interface StockAdjustment {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Kirim pesan WhatsApp test manual dari admin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whatsapp-blast-test".
 */
export interface WhatsappBlastTest {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  storeName?: T;
  logo?: T;
  favicon?: T;
  primaryColor?: T;
  supportEmail?: T;
  paymentConfig?: T;
  emailConfig?: T;
  storageConfig?: T;
  commerce?:
    | T
    | {
        enableUSD?: T;
      };
  trustBadges?:
    | T
    | {
        totalUsers?: T;
        satisfactionRate?: T;
        supportAvailability?: T;
        partnerLogos?:
          | T
          | {
              logo?: T;
              name?: T;
              id?: T;
            };
      };
  legalPages?:
    | T
    | {
        termsPage?: T;
        privacyPage?: T;
        refundPage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-adjustment_select".
 */
export interface StockAdjustmentSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whatsapp-blast-test_select".
 */
export interface WhatsappBlastTestSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}